package in.Btes.placementAutomation.controllers;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;
import in.Btes.placementAutomation.entities.Company;
import in.Btes.placementAutomation.entities.User;
import in.Btes.placementAutomation.repositories.CompanyRepository;
	

	@RestController
	@CrossOrigin(origins = "http://localhost:4200") // This means that this class is a Controller
	@RequestMapping(path="/demo")
	public class CompanyController {
		 @Autowired // This means to get the bean called userRepository
	     // Which is auto-generated by Spring, we will use it to handle the data
		 private CompanyRepository companyRepository;
		 @GetMapping(path="/al")
		   public @ResponseBody Iterable<Company> getAllCompany() {
		     // This returns a JSON or XML with the users
		     return companyRepository.findAll();
		    } 
		 @PostMapping(path="/see")                                     
		   public String addCompany( @RequestBody Company company) {        
			   companyRepository.save(company); 
			   return "saved";
		   }
}


